name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku (using Heroku CLI)
        uses: heroku/login@v1
        with:
          api_token: ${{ secrets.HEROKU_API_TOKEN }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Collect static files (if applicable)
        run: python manage.py collectstatic --no-input
      - name: Deploy to Heroku
        uses: heroku/deploy@v1
        with:
          app_name: django-task-tracker