name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (if pushing image)
        uses: docker/login-action@v2
        with:
          username: '0nk3'
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t 0nk3/django-task-tracker .
      - name: Push Docker image to Docker Hub
        run: docker push 0nk3/django-task-tracker
      - name: Deploy to Heroku (using Heroku CLI)
        uses: akhileshns/heroku-buildpack-docker@v1.4.3  # Switch to this action
        with:
          api_token: ${{ secrets.HEROKU_API_TOKEN }}
          dockerfile: Dockerfile  # Optional, specify Dockerfile path if non-standard
          docker_image: 0nk3/django-task-tracker:latest  # Specify image to pull
      - name: (Optional) Verify deployment (optional)
        run: |
          heroku run python manage.py test  # Example test command
