name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (if pushing image)
        uses: docker/login-action@v2
        with:
          username: 0nk3
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image (optional)
        run: docker build -t 0nk3/django-task-tracker .
      - name: Push Docker image to Heroku Container Registry (optional)
        run: |
          docker tag 0nk3/django-task-track registry.heroku.com/django-task-tracker/web
          docker push registry.heroku.com/django-task-tracker/web
      - name: Deploy to Heroku (using Heroku CLI)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          api_token: ${{ secrets.HEROKU_API_TOKEN }}
          email: '0nk3.0nk3@gmail.com'
          install_node: true  
